# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8c8536da9de72fea3790d1e1f2079dfa59a5369f45b8b7d31987ca0f247ab8f758b6740fb6c0c3c39b42965218d419e0bbe1cd1e96a273fe0fb17415416a4a

test:
  secret_key_base: 93517256ec4f0b4bae4b44149e283dde0ed8d9b70525768952f648fdcbb2301936e83af04cb42fa0c4ed4163c8844a13757713711607ebf003dc9db16270bc7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
